import type { Metadata } from "next";
import { Metrophobic, Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";

const metrophobic = Metrophobic({
  variable: "--font-metrophobic",
  subsets: ["latin"],
  weight: "400"
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-spaceGrotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${metrophobic.variable} ${inter.variable}  ${spaceGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
